FROM python:3.12-slim

#  Ваш код здесь #
WORKDIR /app
# Запускаем приложение с помощью uvicorn, делая его доступным по сети

COPY . . 
# Устанавливаем uvicorn и fastapi явно
RUN pip install --no-cache-dir -r requirements.txt

# Открываем порт 5000
EXPOSE 5000

# Запускаем приложение с полным путем к python
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
